name: cricket
version: "1.0.0"
config-version: 2

profile: cricket

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  snapshot_date: "{{ run_started_at.strftime('%Y-%m-%d') }}"

models:
  cricket:
    staging:
      silver:
        +materialized: view
        +schema: staging
    marts:
      dimensions:
        +materialized: table
        +schema: gold
      facts:
        +materialized: table
        +schema: gold
      analytics:
        +materialized: table
        +schema: gold
